name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: "Lerna Publish"
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[Bump Version]') }}

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}

    - name: "Use NodeJS 16"
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'

    - name: "NPM Identity"
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"

    - name: "Install dependencies"
      run: |
        yarn install

    - name: "TSC"
      run: |
        yarn tsc

    - name: "Build"
      run: |
        yarn build

    - name: Bump Version
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        npx lerna version --conventional-commits --conventional-graduate -m "[Bump Version] %s" --yes
        npx lerna publish from-git --yes
